variable "region" {}
variable "vpc_cidr" {}
variable "profile_name" {}
variable "public_subnet1_cidr" {}
variable "az1" {}
variable "public_subnet2_cidr" {}
variable "az2" {}
variable "app_private_subnet1_cidr" {}
variable "app_private_subnet2_cidr" {}
variable "db_private_subnet1_cidr" {}
variable "db_private_subnet2_cidr" {}
variable "myip"{}
variable "db_identifier" {}
variable "db_storage" {}
variable "db_name" {}
variable "db_engine" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
variable "db_username" {}
variable "db_password" {}
variable "db_replica_identifier" {}
variable "internal_lb_tg" {}
variable "internal_lb_name" {}
variable "app_tier_launch_template_name" {}
variable "app_instance_type" {}
variable "app_tier_ASG_name" {}
variable "max_capactiy_of_app_instances" {}
variable "min_capactiy_of_app_instances" {}
variable "desired_capacity_of_app_instances" {}
variable "interent_facing_lb_TG" {}
variable "internet_facing_lb_name" {}
variable "web_tier_launch_template_name" {}
variable "web_instance_type" {}
variable "web_tier_ASG_name" {}
variable "max_capacity_of_web_insatances" {}
variable "min_capacity_of_web_insatances" {}
variable "desired_capacity_of_web_insatances" {}
variable "web_image_name" {}
variable "app_image_name" {}